//Acciones que describen lo que esta pasando en la aplicacion
//EJEMPLO EL LOGIN DEL USUARIO REALIZAR VERIFICACIONES PARA EJECUTAR FUNCIONES
export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
 