//Acciones que describen lo que esta pasando en la aplicacion
//EJEMPLO EL LOGIN DEL USUARIO REALIZAR VERIFICACIONES PARA EJECUTAR FUNCIONES
export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const AGRERGAR_PROYECTO = 'AGRERGAR_PROYECTO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';